name: Test 
run-name: ${{ github.actor }} is testing
on:
  push:
      branches:
          - 'main'
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                python-version: 3.7 
            - run: python -m pip install --upgrade pip
            - run: pip install pytest 
            - run: pip install -r requirements.txt
            - run: python --version
            - run: pytest --version
            - rn: pytest
    

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: akhileshns/heroku-deploy@v33.12.13 # this is the actions
            - with: 
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "fathomless-headland-72002" 
                heroku_email: "mshahin2@emich.edu"
                usedocker: true